const characters = [
  {name:'엘리시아 아르카벨', role:'학장 · 8써클 시간마법사', group:['faculty'], kicker:'DEAN · THE WITCH OF TIME', tags:['교직원','8써클','시간마법'], appearance:'연보라 장발·청록안·약 8세 외형.', summary:'실제 나이는 300세 이상. 어린아이처럼 자유분방하고 단것을 좋아하며 학생들을 친구처럼 대하지만, 학생의 안전과 성장을 무엇보다 우선한다.', img:0},
  {name:'카르시아 벨로크', role:'무투학부장 · 상급 소드 마스터', group:['faculty'], kicker:'MARTIAL DEAN · IRON-BLOOD SWORD', tags:['교직원','소드 마스터','롱소드'], appearance:'검은 단발·적안·탄탄하고 날렵한 검사 체형.', summary:'롱소드 기본기를 극한까지 다듬은 정통 검사. 냉정하고 엄격하며 화려함보다 정석과 완성도를 중시한다.', img:1},
  {name:'이그니스 벨라트릭스', role:'마법학부장 · 8써클 화룡', group:['faculty'], kicker:'MAGIC DEAN · CRIMSON TYRANT', tags:['교직원','화룡','8써클'], appearance:'붉은 양갈래·금안·검은 뿔·붉은 꼬리·작은 용날개.', summary:'장난스럽고 자유분방하지만 마법의 원리와 실전 판단을 중요하게 본다. 엘리시아와는 오래된 친구.', img:2},
  {name:'아리아 로제트', role:'신성학부장 · 7신위 · 전대 교황', group:['faculty'], kicker:'SACRED DEAN · SAINT OF MERCY', tags:['교직원','7신위','전대 교황'], appearance:'핑크 장발·핑크안, 젊고 온화한 인상.', summary:'치유와 축복에 뛰어나며 흑마법 사용자에게도 편견이 없다. 세렌과 자매처럼 가깝고, 과거 저주 《만독충》에 당한 후유증이 남아 있다.', img:3},
  {name:'카시아 발카인', role:'1학년 · 무투학부', group:['year1'], kicker:'1ST YEAR · MARTIAL FACULTY', tags:['1학년','최상급 소드 유저','검사'], appearance:'빨간 포니테일·적안·탄탄한 전투형 체격.', summary:'무인 명문 백작가 출신. 권위의식은 적으며 강한 상대와의 정면승부를 즐긴다.', img:4},
  {name:'네리아 모르텐', role:'1학년 · 마법학부', group:['year1'], kicker:'1ST YEAR · MAGIC FACULTY', tags:['1학년','2써클','사령술'], appearance:'검은 단발·자안.', summary:'사령술 명문 자작가 출신의 감수성 풍부하고 다정한 마법사. 구울 2체를 운용하며 사령학파를 목표로 한다.', img:5},
  {name:'리아', role:'1학년 · 마법학부', group:['year1'], kicker:'1ST YEAR · MAGIC FACULTY', tags:['1학년','2써클','대지마법'], appearance:'갈색 단발·연두안.', summary:'평민 출신 대지마법사. 극도로 소심하고 따돌림을 겪고 있지만 대지 마법의 재능은 뛰어나며 당당한 세렌을 동경한다.', img:6},
  {name:'세레나 세라프', role:'1학년 · 신성학부', group:['year1'], kicker:'1ST YEAR · SACRED FACULTY', tags:['1학년','2신위','중급 소드 유저'], appearance:'금발 장발·청안.', summary:'성기사 명문가 출신. 책임감이 강하고 수호학파를 목표로 한다. 세렌을 존경하지만 그녀의 행동 방식은 여전히 이해하기 어렵다.', img:7},
  {name:'실피아 에르넬', role:'1학년 · 마법학부', group:['year1'], kicker:'1ST YEAR · SPIRIT USER', tags:['1학년','정령술','실피드'], appearance:'연두 장발·연두안.', summary:'밝고 조금 엉뚱한 정령술사. 중급 바람 정령 실피드와 계약했으며 동화학파를 지망한다.', img:8},
  {name:'에르나 벨로체', role:'1학년 · 마법학부', group:['year1'], kicker:'1ST YEAR · ARTIFACT MAKER', tags:['1학년','마도구','골렘'], appearance:'크림색 포니테일·금안.', summary:'평소에는 무기력하지만 마도구와 골렘 앞에서는 사람이 달라지는 제작광. 거대 골렘 《타이탄》을 제작 중이다.', img:9},
  {name:'엘리제 크로웰', role:'1학년 · 무투학부', group:['year1'], kicker:'1ST YEAR · LONGBOW PRODIGY', tags:['1학년','장궁','십자안'], appearance:'은색 단발·청안, 왼눈에 선천적 《십자안》.', summary:'장궁 저격에 압도적인 재능과 자부심을 지닌 천재 궁수. 석궁을 “근본이 없다”고 낮게 평가한다.', img:10},
  {name:'레오나 바르크', role:'1학년 · 무투학부', group:['year1'], kicker:'1ST YEAR · TIGER BEASTKIN', tags:['1학년','최상급 소드 유저','맨손 격투'], appearance:'금발 장발+검은 브릿지·금안·호랑이 귀와 꼬리·탄탄한 근육질.', summary:'발카르 출신 호랑이 수인. 최상급 소드 유저지만 맨손 격투를 즐기며 강한 상대를 찾아다니는 전투광이다.', img:11},
  {name:'루시아 벨렌', role:'1학년 · 신성학부', group:['year1'], kicker:'1ST YEAR · SACRED CASTER', tags:['1학년','신성마법','신성창'], appearance:'회은색 단발·자안.', summary:'천진난만하고 허당 같지만 《신성창》 실력만큼은 상당하다. 세렌이 유독 귀여워하며 챙기는 후배.', img:12},
  {name:'카밀라 브렌', role:'1학년 · 마법학부', group:['year1'], kicker:'1ST YEAR · BATTLE MAGE', tags:['1학년','2써클','배틀메이지'], appearance:'갈색 땋은 머리·호박안.', summary:'브렌 가문의 사생아. 신체 강화와 이동 마법을 연계한 고속 근접전에 강하며 자신의 실력으로 인정받으려 한다.', img:13},
  {name:'세라피나 루멘하임', role:'1학년 · 신성학부', group:['year1'], kicker:'1ST YEAR · FORMER SAINT CANDIDATE', tags:['1학년','4신위','전 성녀 후보'], appearance:'백금발 장발·금안.', summary:'명문 성직 가문 출신. 누구에게나 자애로운 모범생처럼 보이지만 현 성녀 세렌에 대한 깊은 열등감과 강박을 감추고 있다.', img:14},
  {name:'미레나 벨크', role:'1학년 · 무투학부', group:['year1'], kicker:'1ST YEAR · CROSSBOW SHOOTER', tags:['1학년','석궁','중급 소드 유저'], appearance:'검은 땋은 양갈래·호박안.', summary:'활달하고 말재주 좋은 석궁 사수. 빠른 연사와 마법 볼트를 사용하며 장궁 지상주의자인 엘리제와 자주 티격태격한다.', img:15},
  {name:'아엘리아 실바렌', role:'2학년 · 정령학과', group:['year2'], kicker:'2ND YEAR · HIGH ELF SPIRIT MAGE', tags:['2학년','5써클','하이엘프'], appearance:'금발 웨이브·에메랄드안·뾰족한 하이엘프 귀.', summary:'세계수의 축복을 받은 5써클 정령술사. 차분하고 우아하며 여러 정령과 계약했고 실피아를 귀여운 후배처럼 챙긴다.', img:16},
  {name:'세실리아 로렌', role:'2학년 · 검술학과', group:['year2'], kicker:'2ND YEAR · RAPIER SWORDSMAN', tags:['2학년','최상급 소드 익스퍼트','레이피어'], appearance:'은발 포니테일·남색 눈.', summary:'침착하고 겸손한 훈련광. 레이피어를 이용한 정밀한 찌르기·패링·카운터와 거리 조절에 특화되어 있다.', img:17},
  {name:'이레나 발테르', role:'2학년 · 성기사학과', group:['year2'], kicker:'2ND YEAR · ANTI-MAGIC PALADIN', tags:['2학년','4신위','중급 소드 익스퍼트'], appearance:'짙은 남색 장발·금안.', summary:'네크로맨서에게 가문을 잃은 성기사. 흑마법과 언데드를 증오하며 대마 특화 검술 《멸악검》을 연구한다.', img:18},
  {name:'세이라 블루넬', role:'2학년 · 격투학과', group:['year2'], kicker:'2ND YEAR · GRAPPLER', tags:['2학년','중급 소드 익스퍼트','청류술'], appearance:'검은 단발에 파란 속머리·청안.', summary:'독자적인 《청류술》로 상대의 힘을 흘리고 되돌려 최소한의 움직임으로 제압하는 냉정한 유술가.', img:19},
  {name:'에스텔 루메르', role:'2학년 · 신성마법학과', group:['year2'], kicker:'2ND YEAR · DIVINE BEAST USER', tags:['2학년','3신위','백록'], appearance:'백금빛 단발·연한 청안.', summary:'차분하고 상냥한 신수학파 지망생. 치유 능력을 지닌 중위 신수 흰 사슴 《백록》과 계약했다.', img:20},
  {name:'셀리나 로웬', role:'3학년 · 저주학파', group:['year3'], kicker:'3RD YEAR · CURSE MAGE', tags:['3학년','저주학파','흑마법'], appearance:'핑크 단발·청안.', summary:'밝고 친절한 실전형 흑마법사. 저주·흑마법·사령술을 자유롭게 응용하며 네리아가 동경하는 롤모델이다.', img:21},
  {name:'엘레노어 아르켄', role:'3학년 · 수호학파', group:['year3'], kicker:'3RD YEAR · GUARDIAN PALADIN', tags:['3학년','4신위','상급 소드 익스퍼트'], appearance:'은색 장발·백금안.', summary:'한손검과 대방패, 광역 방어기 《성역》으로 아군의 전선을 지키는 과묵하고 책임감 강한 수호성기사.', img:22},
  {name:'레오니아 에르베인', role:'학생회장 · 황녀', group:['council','year3'], kicker:'STUDENT COUNCIL PRESIDENT · BLAZING PRINCESS', tags:['학생회','3학년','소드 마스터','5써클'], appearance:'금발 장발·적안.', summary:'하급 소드 마스터이자 5써클 마검사. 화염과 빛 마법을 검술에 결합한다. 우아하고 냉정하며 신분보다 실력과 태도로 사람을 판단한다.', img:23},
  {name:'세렌 벨로아', role:'학생회 부회장 · 현 성녀', group:['council','year3'], kicker:'VICE PRESIDENT · SAINT OF THUNDERLIGHT', tags:['학생회','3학년','6신위','천뢰호'], appearance:'옅은 하늘색 단발·금안.', summary:'화끈하고 털털하며 가식 없는 현 성녀. 상위 신수 《천뢰호》와 함께 최전선으로 뛰어들어 신성력을 두른 주먹으로 직접 싸운다.', img:24},
  {name:'세리나 아르벨', role:'학생회 서기 · 포션학파', group:['council','year3'], kicker:'STUDENT COUNCIL SECRETARY', tags:['학생회','3학년','4써클','포션학파'], appearance:'보라 단발·은안·검은 얇은테 안경.', summary:'차분하고 꼼꼼한 학생회 실무의 핵심. 회의록·공문·일정 관리에 능하고 포션 제작에도 정통하다.', img:25},
  {name:'엘리나 골드윈', role:'학생회 회계 · 연금학과', group:['council','year2'], kicker:'STUDENT COUNCIL TREASURER', tags:['학생회','2학년','연금학과','회계'], appearance:'금발 단발·금안.', summary:'돈 자체보다 한정된 자원의 효율적 사용을 중시한다. 낭비에는 냉정하지만 안전·치료·필수 장비에는 비용을 아끼지 않는다.', img:26},
  {name:'아델 크로반', role:'학생회 집행부장 · 투기학파', group:['council','year3'], kicker:'ENFORCEMENT CHIEF · HEAVEN-BORN COVENANT', tags:['학생회','3학년','투기학파','천수언약'], appearance:'검은 포니테일·흑안.', summary:'천수언약으로 마나를 완전히 잃은 대신 초월적인 육체를 얻었다. 과묵하며 특수 에너지 강화 없이 순수한 육체와 격투 기술로 현장을 해결한다.', img:27}
];
const grid=document.getElementById('characterGrid');const modal=document.getElementById('characterModal');
function artStyle(index){const part=index<14?'a':'b';const local=index%14;const c=local%2,r=Math.floor(local/2);const x=c*100,y=(r/6)*100;return `background-image:url('./assets/characters-${part}.webp');background-size:200% 700%;background-position:${x}% ${y}%`;}
function card(c){return `<article class="character-card reveal visible" tabindex="0" role="button" aria-label="${c.name} 상세 보기" data-name="${c.name}"><div class="character-art" style="${artStyle(c.img)}"></div><div class="character-info"><p class="character-role">${c.role}</p><h3>${c.name}</h3><p class="character-summary">${c.summary}</p><div class="card-tags">${c.tags.slice(0,3).map(t=>`<span>${t}</span>`).join('')}</div></div></article>`}
function render(filter='all'){const list=characters.filter(c=>filter==='all'||c.group.includes(filter));grid.innerHTML=list.map(card).join('');grid.querySelectorAll('.character-card').forEach(el=>{const open=()=>openModal(characters.find(c=>c.name===el.dataset.name));el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});});}
function openModal(c){document.getElementById('modalArt').style.cssText=artStyle(c.img);document.getElementById('modalKicker').textContent=c.kicker;document.getElementById('modalName').textContent=c.name;document.getElementById('modalAppearance').textContent=c.appearance;document.getElementById('modalSummary').textContent=c.summary;document.getElementById('modalTags').innerHTML=c.tags.map(t=>`<span>${t}</span>`).join('');modal.showModal();}
render();document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');render(btn.dataset.filter);}));document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.open)modal.close()});document.querySelectorAll('.glossary-toggle').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.glossary-card');const open=card.classList.toggle('open');btn.setAttribute('aria-expanded',open);}));const toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('.site-nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));const sections=[...document.querySelectorAll('main section[id]')];const navLinks=[...document.querySelectorAll('.site-nav a')];const navObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`));}})},{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>navObserver.observe(s));